version: '3.8'

services:
  backend:
    build: ./backend
    container_name: decision_backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: decision_frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
